# Generated by Django 4.1 on 2022-08-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_ordered_date_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
    ]
